### ISSUE TITLE
微信群，差评

### ISSUE THREAD

**Issue by miaoyuxinbaby** [BestDingSheng/resources#1]
``

**Comment by BestDingSheng** [comment]
@miaoyuxinbaby  有什么好的建议吗 ~

**Comment by miaoyuxinbaby** [comment]
@BestDingSheng 当然是扣扣群呀。扣扣群可以随时查看群公告，群文件，设置特别关心，屏蔽等，还能各种花式操作。微信群操作太抠脚了。

**Comment by BestDingSheng** [comment]
@miaoyuxinbaby  好吧 ~ 之前调查过一次 70%的人不愿意用qq群 ，其实我本人也不太愿意使用！ 现在人越来越多后面会考下弄个QQ群吧 ~  感谢建议
