### ISSUE TITLE
微信群质量差 人品更差

### ISSUE THREAD

**Issue by jimmy2011617** [BestDingSheng/resources#10]
加入此人搞的内推(此处有大佬)时付过60，但质量每况愈下，而且群中根本没有所谓的互联网大佬，向此人提出退群即可拉黑，几十元钱看清一个人蛮便宜的，引以为戒凡是向你收费的微信群不要加
![image](https://user-images.githubusercontent.com/47397380/73122001-75bcdd00-3fba-11ea-8f8a-ff039aeab54e.png)
![image](https://user-images.githubusercontent.com/47397380/73122006-82d9cc00-3fba-11ea-9aee-fd9c2c3d99b1.png)

**Comment by BestDingSheng** [comment]
此群是我2018年5月份创立，当时都是自愿付费入群，时隔两年 ~  这位同学在群里 ，发布疫情谣言还辱骂去群友 ，被我T出此群 ，然后还问我退钱 要不要点脸，你要没错 你截图上打什么码？
![image](https://user-images.githubusercontent.com/13111768/73135373-3eaf0000-407c-11ea-91fb-504da70a2071.png)
